name: Update File Count in README

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Count Files
        run: echo "File count: $(git ls-files | wc -l)" > filecount.txt

      - name: Update README
        run: sed -i 's/This repository contains .*/This repository contains **$(cat filecount.txt)** files./' README.md

      - name: Commit Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update file count in README"
          git push
